version: "3.7"
services:
  api1:
    image: api1:latest
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 256M
          cpus: "1"
      restart_policy:
        condition: on-failure
    ports:
      - "8000:8000"
  
  api2:
    image: api2:latest
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 256M
          cpus: "1"
      restart_policy:
        condition: on-failure
    ports:
      - "8001:8000"