version: "3.7"
services:
  apache:
    image: httpd:latest
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 128M
          cpus: "0.5"
      restart_policy:
        condition: on-failure
    ports:
      - "8080:80"
    configs:
      - source: apache_config
        target: /usr/local/apache2/conf/httpd.conf
        mode: 0440
  django:
    image: django:latest
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 256M
          cpus: "1"
      restart_policy:
        condition: on-failure
    ports:
      - "8081:8000"
    configs:
      - source: django_config
        target: /app/settings.py
        mode: 0440
  mysql:
    image: mysql:5.7
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M
          cpus: "1"
      restart_policy:
        condition: on-failure
    volumes:
      - mysql_data:/var/lib/mysql
    secrets:
      - mysql_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_DATABASE: mydb
secrets:
  mysql_password:
    external: true
configs:
  apache_config:
    external: true
  django_config:
    external: true