version: "3.7"
services:
  nginx:
    image: nginx:latest
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 128M
          cpus: "0.5"
      restart_policy:
        condition: on-failure
    ports:
      - "8081:80"
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
        mode: 0440
  mysql:
    image: mysql:5.7
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M
          cpus: "1"
      restart_policy:
        condition: on-failure
    volumes:
      - mysql_data:/var/lib/mysql
    secrets:
      - mysql_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_DATABASE: mydb
secrets:
  mysql_password:
    external: true
configs:
  nginx_config:
    external: true